controle/urls.py
from django.urls import path, include
from . import views
from controle.views import (
    IndividuoListView,
    IndividuoCreateView,
    IndividuoUpdateView,
    IndividuoDeleteView,
    IndividuoDetailView,
    OrcrimListView,
    OrcrimCreateView,
    OrcrimUpdateView,
    OrcrimDeleteView,
    CasaPrisionalListView,
    CasaPrisionalCreateView,
    CasaPrisionalUpdateView,
    CasaPrisionalDeleteView,
    individuos_por_orcrim,
    organograma_view,
    orcrim_list,
)

urlpatterns = [
    # URLs para Individuo
    path("visualizar_individuos/", IndividuoListView.as_view(), name="individuo_list"),
    path(
        "individuo/<int:pk>/",
        IndividuoDetailView.as_view(),
        name="individuo_detail",
    ),
    path("adicionar_individuo/", IndividuoCreateView.as_view(), name="individuo_add"),
    path(
        "editar_individuo/<int:pk>/",
        IndividuoUpdateView.as_view(),
        name="individuo_edit",
    ),
    path(
        "deletar_individuo/<int:pk>/",
        IndividuoDeleteView.as_view(),
        name="individuo_delete",
    ),
    # URLs para Orcrim
    path("visualizar_orcrims/", OrcrimListView.as_view(), name="orcrim_list"),
    path("adicionar_orcrim/", OrcrimCreateView.as_view(), name="orcrim_add"),
    path(
        "editar_orcrim/<int:pk>/",
        OrcrimUpdateView.as_view(),
        name="orcrim_edit",
    ),
    path(
        "deletar_orcrim/<int:pk>/",
        OrcrimDeleteView.as_view(),
        name="orcrim_delete",
    ),
    # URLs para Casa Prisional
    path(
        "visualizar_casas_prisionais/",
        CasaPrisionalListView.as_view(),
        name="casaprisional_list",
    ),
    path(
        "adicionar_casa_prisional/",
        CasaPrisionalCreateView.as_view(),
        name="casaprisional_add",
    ),
    path(
        "editar_casa_prisional/<int:pk>/",
        CasaPrisionalUpdateView.as_view(),
        name="casaprisional_edit",
    ),
    path(
        "deletar_casa_prisional/<int:pk>/",
        CasaPrisionalDeleteView.as_view(),
        name="casaprisional_delete",
    ),
    path("ajax/pavilhoes/", views.carregar_pavilhoes, name="carregar_pavilhoes"),
    path("ajax/galerias/", views.carregar_galerias, name="carregar_galerias"),
    path("ajax/celas/", views.carregar_celas, name="carregar_celas"),
    path("ajax/alojamentos/", views.carregar_alojamentos, name="carregar_alojamentos"),
    # AJAX para tipo de estrutura da casa prisional
    path("ajax/tipo_estrutura/", views.tipo_estrutura_view, name="tipo_estrutura"),
    # AJAX para carregar dados diretamente por casa prisional
    path("ajax/galerias_por_casa/", views.carregar_galerias, name="galerias_por_casa"),
    path("ajax/celas_por_casa/", views.carregar_celas, name="celas_por_casa"),
    path(
        "ajax/alojamentos_por_casa/",
        views.carregar_alojamentos,
        name="alojamentos_por_casa",
    ),
    # Organograma
    # URL para a página que exibe o organograma
    path("organograma/", views.organograma_view, name="organograma"),
    # URL da API para listar todas as Orcrims (Organizações Criminosas)
    path("api/orcrim/", views.orcrim_list, name="api_orcrim_list"),
    # URL da API para buscar os indivíduos de uma Orcrim específica
    path(
        "api/orcrim/<int:orcrim_id>/individuos/",
        views.individuos_por_orcrim,
        name="individuos_por_orcrim",
    ),
    # URL para listar indivíduos por galeria
    path('selecionar-presidio/', views.selecionar_presidio, name='selecionar_presidio'),
    path('galeria/<int:galeria_id>/detentos/', views.listar_detentos_por_galeria, name='listar_detentos_por_galeria'),
]

orcrim/urls.py
from django.contrib import admin
from django.urls import path, include
from controle import views
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include("controle.urls")),
    path("", views.home, name="home"),
    # path("organograma/", include("controle.urls")),
]

# Adiciona URLs para servir arquivos de mídia durante o desenvolvimento
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)


handler404 = "controle.views.not_found"

controle/models.py
from django.db import models
from django.core.exceptions import ValidationError

# Choices para campos específicos
SITUACAO_CHOICES = [
    ("recolhido", "Recolhido"),
    ("recolhido_tornozeleira", "Recolhido - Tornozeleira"),
    ("liberdade", "Liberdade"),
    ("foragido", "Foragido"),
    ("removido", "Removido"),
    ("procurado", "Procurado"),
]

REGIME_CHOICES = [
    ("fechado", "Fechado"),
    ("semiaberto", "Semiaberto"),
    ("aberto", "Aberto"),
    ("provisorio", "Provisório"),
    ("monitorado", "Monitorado"),
    ("sem regime", "Sem Regime"),
]

ORCRIM_ABRANGENCIA_CHOICES = [
    ("ocl", "OCL"),
    ("ocr", "OCR"),
    ("ocn", "OCN"),
    ("oci", "OCI"),
    ("nao_possui", "Não possui"),
]

DELEGACIAS_PENITENCIARIAS_CHOICES = [
    ("1dpr", "1ª DPR"),
    ("2dpr", "2ª DPR"),
    ("3dpr", "3ª DPR"),
    ("4dpr", "4ª DPR"),
    ("5dpr", "5ª DPR"),
    ("6dpr", "6ª DPR"),
    ("7dpr", "7ª DPR"),
    ("8dpr", "8ª DPR"),
    ("9dpr", "9ª DPR"),
    ("10dpr", "10ª DPR"),
    ("unid_esp", "Unidades Especiais"),
]


TIPO_ESTRUTURA_CHOICES = [
    ("completa", "Completa (Pavilhão, Galeria, Cela)"),  # Sem alojamento/módulo
    (
        "intermediaria",
        "Intermediária (Galeria, Cela)",
    ),  # Sem pavilhão, alojamento/módulo
    ("pavilhao", "Pavilhão"),  # Detalhar se necessário
    ("modular", "Módulo"),  # Detalhar se necessário
    ("apenas_alojamento", "Apenas Alojamento"),  # Sem pavilhão/galeria/cela
]

NIVEL_CHOICES = (
    ("lider", "Líder"),
    ("influente", "Influente"),
    ("sem_expressao", "Sem Expressão"),
)


class Cidade(models.Model):
    nome = models.CharField(max_length=100, verbose_name="Nome da Cidade")

    class Meta:
        verbose_name = "Cidade"
        verbose_name_plural = "Cidades"

    def __str__(self):
        return self.nome


class Orcrim(models.Model):
    nome = models.CharField(max_length=100, verbose_name="Nome da Orcrim")
    sigla = models.CharField(max_length=30, verbose_name="Sigla", blank=True, null=True)
    area_abrangencia = models.CharField(
        max_length=30,
        choices=ORCRIM_ABRANGENCIA_CHOICES,
        verbose_name="Área de Abrangência",
    )
    logo_orcrim = models.ImageField(
        upload_to="fotos/", blank=True, null=True, verbose_name="Logo da Orcrim"
    )

    class Meta:
        verbose_name = "Orcrim"
        verbose_name_plural = "Orcrims"

    def __str__(self):
        return self.nome


class CasaPrisional(models.Model):
    nome = models.CharField(max_length=100, verbose_name="Nome da Casa Prisional")
    sigla = models.CharField(max_length=20, verbose_name="Sigla")
    cidade = models.ForeignKey(Cidade, on_delete=models.SET_NULL, null=True)
    delegacia_penitenciaria = models.CharField(
        max_length=20,
        choices=DELEGACIAS_PENITENCIARIAS_CHOICES,
        verbose_name="Delegacia Penitenciária",
    )
    tipo_estrutura = models.CharField(
        max_length=100,
        choices=TIPO_ESTRUTURA_CHOICES,
        default="completa",
        verbose_name="Tipo de Estrutura",
    )

    class Meta:
        verbose_name = "Casa Prisional"
        verbose_name_plural = "Casas Prisionais"

    def __str__(self):
        return f"{self.sigla} - {self.nome}"


class Pavilhao(models.Model):
    casa_prisional = models.ForeignKey(CasaPrisional, on_delete=models.CASCADE)
    nome = models.CharField(
        max_length=100, verbose_name="Pavilhão", null=True, blank=True
    )

    class Meta:
        verbose_name = "Pavilhão"
        verbose_name_plural = "Pavilhões"

    def __str__(self):
        return f"{self.nome} - {self.casa_prisional.nome}"


class Galeria(models.Model):
    casa_prisional = models.ForeignKey(CasaPrisional, on_delete=models.CASCADE)
    pavilhao = models.ForeignKey(
        Pavilhao, on_delete=models.CASCADE, null=True, blank=True
    )
    nome = models.CharField(
        max_length=100, verbose_name="Galeria", null=True, blank=True
    )
    orcrim = models.ForeignKey(
        "Orcrim",
        on_delete=models.SET_NULL,
        null=True,
        blank=True,
        verbose_name="Orcrim Relacionada",
    )

    class Meta:
        verbose_name = "Galeria"
        verbose_name_plural = "Galerias"

    def __str__(self):
        return f"{self.nome} - {self.casa_prisional.nome}"


class Cela(models.Model):
    casa_prisional = models.ForeignKey(
        CasaPrisional,
        on_delete=models.CASCADE,
    )
    pavilhao = models.ForeignKey(
        Pavilhao, on_delete=models.CASCADE, null=True, blank=True
    )
    galeria = models.ForeignKey(
        Galeria, on_delete=models.CASCADE, null=True, blank=True
    )
    numero = models.CharField(max_length=10, verbose_name="Cela", null=True, blank=True)

    class Meta:
        verbose_name = "Cela"
        verbose_name_plural = "Celas"

    def __str__(self):
        return self.numero


class Alojamento(models.Model):
    casa_prisional = models.ForeignKey(CasaPrisional, on_delete=models.CASCADE)
    pavilhao = models.ForeignKey(
        Pavilhao, on_delete=models.CASCADE, null=True, blank=True
    )
    galeria = models.ForeignKey(
        Galeria, on_delete=models.CASCADE, null=True, blank=True
    )
    cela = models.ForeignKey(Cela, on_delete=models.CASCADE, null=True, blank=True)
    nome = models.CharField(max_length=100, verbose_name="Alojamento", blank=True)
    orcrim = models.ForeignKey(
        "Orcrim",
        on_delete=models.SET_NULL,
        null=True,
        blank=True,
        verbose_name="Orcrim Relacionada",
    )

    class Meta:
        verbose_name = "Alojamento"
        verbose_name_plural = "Alojamentos"

    def __str__(self):
        return self.nome


class Individuo(models.Model):
    nome = models.CharField(max_length=100, verbose_name="Nome Completo")
    rg_cpf = models.CharField(max_length=14, verbose_name="RG/CPF", unique=True)
    data_nasc = models.DateField()
    alcunha = models.CharField(
        max_length=100, blank=True, null=True, verbose_name="Alcunha"
    )
    codigo_detento = models.CharField(
        max_length=8, blank=True, null=True, verbose_name="Cód."
    )
    foto = models.ImageField(
        upload_to="fotos/", blank=True, null=True, verbose_name="Foto"
    )
    situacao_penal = models.CharField(
        max_length=50, choices=SITUACAO_CHOICES, verbose_name="Situação Penal"
    )
    orcrim = models.ForeignKey(
        Orcrim, on_delete=models.SET_NULL, null=True, blank=True, verbose_name="Orcrim"
    )
    regime = models.CharField(
        max_length=50, choices=REGIME_CHOICES, verbose_name="Regime"
    )
    casa_prisional = models.ForeignKey(
        CasaPrisional, on_delete=models.SET_NULL, null=True, blank=True
    )
    pavilhao = models.ForeignKey(
        Pavilhao, on_delete=models.SET_NULL, null=True, blank=True
    )
    galeria = models.ForeignKey(
        Galeria, on_delete=models.SET_NULL, null=True, blank=True
    )
    cela = models.ForeignKey(Cela, on_delete=models.SET_NULL, null=True, blank=True)
    alojamento = models.ForeignKey(
        Alojamento, on_delete=models.SET_NULL, null=True, blank=True
    )
    observacao = models.CharField(max_length=150, null=True, blank=True)
    nivel_orcrim = models.CharField(
        max_length=20,
        choices=NIVEL_CHOICES,
        default="sem_expressao",  # Adicione um valor padrão
        verbose_name="Nível de Hierarquia na Orcrim",
    )

    @property
    def foto_url(self):
        if self.foto and hasattr(self.foto, "url"):
            return self.foto.url
        return "/static/images/default_photo.png"

    class Meta:
        verbose_name = "Indivíduo"
        verbose_name_plural = "Indivíduos"

    def __str__(self):
        return self.nome

controle/templates/individuo/individuo_confirm_delete.html
{% extends "base.html" %}
{% load static %}

{% block title %}Excluir Indivíduo{% endblock %} 

{% block content %}
    <h1>Exclusão de Indivíduo</h1>
    <p>Tem certeza que deseja excluir o Indivíduo "{{ individuo.nome }}"?</p>
    <form method="post">
        {% csrf_token %}
        <button type="submit" class="btn btn-danger">Confirmar Exclusão</button>
        <a href="{% url 'individuo_list' %}" class="btn btn-secondary">Cancelar</a>
    </form>
{% endblock content %}

controle/templates/individuo/individuo_detail.html
{% extends "base.html" %}
{% load format_filters %}
{% load static %}


{% block title %}Detalhes - {{ individuo.nome }}{% endblock %} 

{% block extra_head_css %}
    <link rel="stylesheet" href="{% static 'controle/css/individuo_detail.css' %}">
{% endblock %}

{% block content %}
<title>Detalhes do Indivíduo</title>


<div class="card shadow-lg mb-4">
    <div class="card-header text-bg-info text-center">
        <h3 class="mb-0">Detalhes de: <strong>{{ individuo.nome }}</strong></h3>
    </div>
    
    <div class="card-body">
        
        <div class="text-center mb-4">
            {% if individuo.foto %}
                <img src="{{ individuo.foto.url }}" 
                     alt="{{ individuo.nome }}" 
                     class="img-fluid rounded-circle border border-5 border-light" 
                     style="width: 150px; height: 150px; object-fit: cover;">
            {% else %}
                <div class="bg-light text-muted p-4 rounded-circle d-inline-block border border-3 border-secondary" style="width: 150px; height: 150px; line-height: 120px;">
                    Sem Foto
                </div>
            {% endif %}
        </div>
        
        <hr>
        
        <div class="d-flex justify-content-between align-items-start">
            
            <dl class="row w-75"> 
                {% if individuo.rg_cpf|length == 10 %}
                    <dt class="col-sm-4">RG</dt>
                {% elif individuo.rg_cpf|length == 11 %}
                    <dt class="col-sm-4">CPF</dt>
                {% else %}
                    <dt class="col-sm-4">RG/CPF</dt>
                {% endif %}
                <dd class="col-sm-8">{{ individuo.rg_cpf|formatar_cpf_rg|default:"Não Informado" }}</dd>
                
                <dt class="col-sm-4">Data de Nascimento</dt>
                <dd class="col-sm-8">{{ individuo.data_nasc|date:"d/m/Y" }}</dd> 

                {% if individuo.alcunha %}
                <dt class="col-sm-4">Alcunha</dt>
                <dd class="col-sm-8">{{ individuo.alcunha}}</dd>
                {% endif %}

                <dt class="col-sm-4">Cód. Detento/Preso</dt>
                <dd class="col-sm-8">{{ individuo.codigo_detento|default:"N/A" }}</dd>

                <dt class="col-sm-4">Organização Criminosa</dt>
                <dd class="col-sm-8">
                    {% if individuo.orcrim %}
                        <strong>{{ individuo.orcrim.nome }}</strong>
                    {% else %}
                        Sem Orcrim Associada
                    {% endif %}
                </dd>

                <dt class="col-sm-4">Nível na Orcrim</dt>
                <dd class="col-sm-8">{{ individuo.get_nivel_orcrim_display|default:"N/A" }}</dd>

                <dt class="col-sm-4">Situação Penal</dt>
                <dd class="col-sm-8">
                    <span class="badge 
                        {% if individuo.situacao_penal == 'recolhido' %} text-bg-danger
                        {% elif individuo.situacao_penal == 'recolhido_tornozeleira' %} text-bg-primary
                        {% elif individuo.situacao_penal == 'liberdade' %} text-bg-success
                        {% elif individuo.situacao_penal == 'foragido' %} text-bg-warning
                        {% elif individuo.situacao_penal == 'procurado' %} text-bg-warning
                        {% elif individuo.situacao_penal == 'removido' %} text-bg-gray
                        {% else %} text-bg-secondary
                        {% endif %}">
                        {{ individuo.get_situacao_penal_display }} - {{ individuo.casa_prisional|default:'' }}
                    </span>
                </dd>

                <dt class="col-sm-4">Regime</dt>
                <dd class="col-sm-8">{{ individuo.get_regime_display|default:"" }}</dd>

                {% if individuo.pavilhao%}
                <dt class="col-sm-4">Pavilhão</dt>
                <dd class="col-sm-8">{{ individuo.pavilhao|default:"" }}</dd>
                {% endif %}

                {% if individuo.galeria %}
                <dt class="col-sm-4">Galeria</dt>
                <dd class="col-sm-8">{{ individuo.galeria|default:"" }}</dd>
                {% endif %}

                {% if individuo.cela %}
                <dt class="col-sm-4">Cela</dt>
                <dd class="col-sm-8">{{ individuo.cela|default:"" }}</dd>
                {% endif %}

                {% if individuo.alojamento %}
                <dt class="col-sm-4">Alojamento</dt>
                <dd class="col-sm-8">{{ individuo.alojamento|default:"" }}</dd>
                {% endif %}
                
            </dl>
            
            <div id="logo-orcrim" class="flex-shrink-0 text-center ms-3">
                {% if individuo.orcrim.logo_orcrim %}
                    <p class="mb-1 text-muted small">Logo da Orcrim:</p>
                    <img src="{{ individuo.orcrim.logo_orcrim.url }}" style="max-width: 200px; height: auto; border: 1px solid #ddd; padding: 5px;">
                {% else %}
                    <span class="text-muted small">Sem Logo</span>
                {% endif %}
            </div>
            
        </div>
        </div>
    <div class="card-footer text-end">
        <a href="{% url 'individuo_list' %}" class="btn btn-secondary me-2">
            <i class="fas fa-arrow-left"></i> Voltar
        </a>
        {# <a href="{% url 'individuo_update' individuo.pk %}" class="btn btn-primary">Editar</a> #}
    </div>
    
</div>
{% endblock content %}

controle/templates/individuo/listar_detentos.html
{% extends "base.html" %}
{% load static %}
{% load format_filters %}

{% block title %}Detalhes{% endblock %} 

{% block content %}
<div class="card">
  <div class="card-body text-bg-primary p-3 text-center">
    <h3 class="text-center">Detentos na Galeria {{ galeria.nome }} - {{ galeria.casa_prisional.nome }} ({{ galeria.casa_prisional.sigla }})</h3>
  </div>
</div>
<br>    
       <a href="{% url 'selecionar_presidio' %}"><i class="bi bi-arrow-return-left"></i> Voltar</a>
    {% if detentos %}
        <table class="table table-striped table-hover">
            <thead class="table-dark text-center">
                <tr class="align-middle">
                    <th>Foto</th>
                    <th>Nome</th>
                    <th>RG/CPF</th>
                    <th>Data de Nascimento</th>
                    <th>Alcunha</th>
                    <th>Situação Penal</th>
                    <th>Orcrim</th>
                    <th>Regime</th>
                </tr>
            </thead>
            <tbody>
                {% for detento in detentos %}
                    <tr class="align-middle">
                        <td class="text-center">
                            {% if detento.foto %}
                                <img src="{{ detento.foto.url }}" alt="Foto de {{ detento.nome }}" width="50" height="50">
                            {% else %}
                                Sem foto
                            {% endif %}
                        </td>
                        <td>{{ detento.nome }}</td>
                        <td>{{ detento.rg_cpf|formatar_cpf_rg|default:"Não Informado" }}</td>
                        <td class="text-center">{{ detento.data_nasc|date:"d/m/Y" }}</td>
                        <td class="text-center">{{ detento.alcunha|default:"N/A"}}</td>
                        <td class="text-center">
                            {% with detento.situacao_penal as status %}
                            {% if status == 'liberdade' %}
                            <span class="badge text-bg-success">{{ detento.get_situacao_penal_display }}</span>
                            {% elif status == 'recolhido' %}
                            <span class="badge text-bg-danger">{{ detento.get_situacao_penal_display }}</span>
                            {% elif status == 'recolhido_tornozeleira' %}
                            <span class="badge text-bg-info">{{ detento.get_situacao_penal_display }}</span>
                            {% elif status == 'foragido' %}
                            <span class="badge text-bg-warning">{{ detento.get_situacao_penal_display }}</span>
                            {% elif status == 'removido' %}
                            <span class="badge text-bg-secondary">{{ detento.get_situacao_penal_display }}</span>
                            {% else %}
                            <span class="badge text-bg-light">{{ detento.get_situacao_penal_display }}</span>
                            {% endif %}
                            {% endwith %}
                        </td>
                        <td class="text-center">{{ detento.orcrim|default:"N/A" }}</td>
                        <td class="text-center">{{ detento.get_regime_display }}</td>
                    </tr>
                {% endfor %}
            </tbody>
        </table>
    {% else %}
        <p>Nenhum detento encontrado nesta galeria.</p>
    {% endif %}
 
{% endblock %}

controle/templates/individuo/selecionar_presidio.html
{% extends "base.html" %}
{% load static %}

{% block title %}Detalhes dos Presídios{% endblock %}

{% block content %}
<div class="card">
  <div class="card-body text-bg-primary p-3 text-center">
    <h3>Casas Prisionais</h3>
  </div>
</div>
<br>
<div class="accordion accordion-flush" id="presidiosAccordion">
    {% if presidios %}
        {% for presidio in presidios %}
            <div class="accordion-item">
                <h2 class="accordion-header">
                    <button class="accordion-button collapsed" type="button" data-bs-toggle="collapse" data-bs-target="#flush-collapse-{{ presidio.id }}" aria-expanded="false" aria-controls="flush-collapse-{{ presidio.id }}">
                        {{ presidio.sigla }} - {{ presidio.nome }}
                    </button>
                </h2>
                <div id="flush-collapse-{{ presidio.id }}" class="accordion-collapse collapse" data-bs-parent="#presidiosAccordion">
                    <div class="accordion-body">
                        {% if presidio.galeria_set.all %}
                            <ul class="list-group list-group-flush">
                                {% for galeria in presidio.galeria_set.all %}
                                    <li class="list-group-item d-flex justify-content-between align-items-start flex-column">
                                        <!-- Informações da Galeria -->
                                        <div class="d-flex justify-content-between w-100 align-items-center mb-2">
                                            <div>
                                                <strong>Galeria:</strong> {{ galeria.nome }} {{ galeria.pavilhao.nome }} - {{ galeria.orcrim }}
                                            </div>
                                            <!-- Botão Ver Detentos -->
                                            <a href="{% url 'listar_detentos_por_galeria' galeria.id %}" class="btn btn-sm btn-outline-primary">
                                                <i class="bi bi-person-vcard"></i> Ver Detentos
                                            </a>
                                        </div>

                                        <!-- **INÍCIO DA LISTAGEM DOS ALOJAMENTOS** -->
                                        {% if galeria.alojamento_set.all %}
                                            <div class="w-100 mt-2">
                                                <small class="text-muted d-block mb-1">Alojamentos:</small>
                                                <ul class="list-group list-group-horizontal flex-wrap">
                                                    {% for alojamento in galeria.alojamento_set.all %}
                                                        <li class="list-group-item list-group-item-action list-group-item-light border py-1 px-2 me-1 mb-1 rounded">
                                                            {{ alojamento.nome }} <!-- AGORA USANDO alojamento.nome -->
                                                        </li>
                                                    {% endfor %}
                                                </ul>
                                            </div>
                                        {% else %}
                                            
                                        {% endif %}
                                        <!-- **FIM DA LISTAGEM DOS ALOJAMENTOS** -->

                                    </li>
                                {% endfor %}
                            </ul>
                        {% else %}
                            <p>Nenhuma galeria cadastrada para este presídio.</p>
                        {% endif %}
                    </div>
                </div>
            </div>
        {% endfor %}
    {% else %}
        <div class="alert alert-warning" role="alert">
            Nenhum presídio cadastrado.
        </div>
    {% endif %}
</div>
{% endblock %}